// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UISTask.Infrastructure.Data.Context;

#nullable disable

namespace UISTask.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241028111335_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UISTask.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ef287483-7d67-4754-8029-74b7a7adda24"),
                            CurrentQuantity = 100,
                            InitialQuantity = 100,
                            Price = 10.5m,
                            ProductName = "Product A",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("492296e5-0e71-44fb-ab9c-8bc7245a9e57"),
                            CurrentQuantity = 200,
                            InitialQuantity = 200,
                            Price = 2.0m,
                            ProductName = "Product B",
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = new Guid("5fca2a63-62a7-40ec-a49d-40aad2205669"),
                            CurrentQuantity = 50,
                            InitialQuantity = 50,
                            Price = 5.0m,
                            ProductName = "Product C",
                            Unit = "liters"
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.ProductTransaction", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ProductTransactions");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("ef287483-7d67-4754-8029-74b7a7adda24"),
                            TransactionId = new Guid("49aabfd4-a5e0-4ea7-a47c-6b9ea37e8fc8"),
                            Quantity = 10,
                            TotalPrice = 105.0m
                        },
                        new
                        {
                            ProductId = new Guid("492296e5-0e71-44fb-ab9c-8bc7245a9e57"),
                            TransactionId = new Guid("49aabfd4-a5e0-4ea7-a47c-6b9ea37e8fc8"),
                            Quantity = 20,
                            TotalPrice = 40.0m
                        },
                        new
                        {
                            ProductId = new Guid("ef287483-7d67-4754-8029-74b7a7adda24"),
                            TransactionId = new Guid("59aa9924-a049-4fc9-81b6-abe621b687fb"),
                            Quantity = 5,
                            TotalPrice = 52.5m
                        },
                        new
                        {
                            ProductId = new Guid("5fca2a63-62a7-40ec-a49d-40aad2205669"),
                            TransactionId = new Guid("e0230965-9379-4d03-bfae-be9792d9d790"),
                            Quantity = 15,
                            TotalPrice = 75.0m
                        },
                        new
                        {
                            ProductId = new Guid("492296e5-0e71-44fb-ab9c-8bc7245a9e57"),
                            TransactionId = new Guid("abad5e33-0615-4d14-a9ff-691910864115"),
                            Quantity = 30,
                            TotalPrice = 60.0m
                        },
                        new
                        {
                            ProductId = new Guid("5fca2a63-62a7-40ec-a49d-40aad2205669"),
                            TransactionId = new Guid("222d8ae7-e4f1-47ed-a7bf-a0305a6917b6"),
                            Quantity = 25,
                            TotalPrice = 125.0m
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("49aabfd4-a5e0-4ea7-a47c-6b9ea37e8fc8"),
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("59aa9924-a049-4fc9-81b6-abe621b687fb"),
                            Date = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e0230965-9379-4d03-bfae-be9792d9d790"),
                            Date = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("abad5e33-0615-4d14-a9ff-691910864115"),
                            Date = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("222d8ae7-e4f1-47ed-a7bf-a0305a6917b6"),
                            Date = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.ProductTransaction", b =>
                {
                    b.HasOne("UISTask.Domain.Entities.Product", "Product")
                        .WithMany("ProductTransaction")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UISTask.Domain.Entities.Transaction", "Transaction")
                        .WithMany("ProductTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductTransaction");
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("ProductTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
