// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UISTask.Infrastructure.Data.Context;

#nullable disable

namespace UISTask.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20241025163716_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UISTask.Domain.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8107907a-eeba-4b65-a337-19e64473f454"),
                            CurrentQuantity = 100,
                            InitialQuantity = 100,
                            Price = 10.5m,
                            ProductName = "Product A",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("2bf41594-840a-4093-a789-bf2b25f7f5f3"),
                            CurrentQuantity = 200,
                            InitialQuantity = 200,
                            Price = 2.0m,
                            ProductName = "Product B",
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = new Guid("f97caed1-cbcb-4ad7-a06f-502a5dadaf1a"),
                            CurrentQuantity = 50,
                            InitialQuantity = 50,
                            Price = 5.0m,
                            ProductName = "Product C",
                            Unit = "liters"
                        });
                });

            modelBuilder.Entity("UISTask.Domain.ProductTransaction", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ProductTransactions");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("8107907a-eeba-4b65-a337-19e64473f454"),
                            TransactionId = new Guid("ebe183af-678e-4446-b25a-55e31567a64c"),
                            Quantity = 10,
                            TotalPrice = 105.0m
                        },
                        new
                        {
                            ProductId = new Guid("2bf41594-840a-4093-a789-bf2b25f7f5f3"),
                            TransactionId = new Guid("ebe183af-678e-4446-b25a-55e31567a64c"),
                            Quantity = 20,
                            TotalPrice = 40.0m
                        },
                        new
                        {
                            ProductId = new Guid("8107907a-eeba-4b65-a337-19e64473f454"),
                            TransactionId = new Guid("04bf5f1e-6486-4cb0-83e2-0255bf5ab0d2"),
                            Quantity = 5,
                            TotalPrice = 52.5m
                        },
                        new
                        {
                            ProductId = new Guid("f97caed1-cbcb-4ad7-a06f-502a5dadaf1a"),
                            TransactionId = new Guid("e9758d9e-9f5b-42a9-b6c1-98dd3f5c3572"),
                            Quantity = 15,
                            TotalPrice = 75.0m
                        },
                        new
                        {
                            ProductId = new Guid("2bf41594-840a-4093-a789-bf2b25f7f5f3"),
                            TransactionId = new Guid("4b2d8a78-0eef-46b2-b3ef-db94d5fca01a"),
                            Quantity = 30,
                            TotalPrice = 60.0m
                        },
                        new
                        {
                            ProductId = new Guid("f97caed1-cbcb-4ad7-a06f-502a5dadaf1a"),
                            TransactionId = new Guid("5cb414ee-f832-49eb-a87d-3561ea59eb81"),
                            Quantity = 25,
                            TotalPrice = 125.0m
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ebe183af-678e-4446-b25a-55e31567a64c"),
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("04bf5f1e-6486-4cb0-83e2-0255bf5ab0d2"),
                            Date = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("e9758d9e-9f5b-42a9-b6c1-98dd3f5c3572"),
                            Date = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("4b2d8a78-0eef-46b2-b3ef-db94d5fca01a"),
                            Date = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("5cb414ee-f832-49eb-a87d-3561ea59eb81"),
                            Date = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UISTask.Domain.ProductTransaction", b =>
                {
                    b.HasOne("UISTask.Domain.Product", "Product")
                        .WithMany("ProductTransaction")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UISTask.Domain.Transaction", "Transaction")
                        .WithMany("ProductTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("UISTask.Domain.Product", b =>
                {
                    b.Navigation("ProductTransaction");
                });

            modelBuilder.Entity("UISTask.Domain.Transaction", b =>
                {
                    b.Navigation("ProductTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
