// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UISTask.Infrastructure.Data.Context;

#nullable disable

namespace UISTask.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UISTask.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CurrentQuantity")
                        .HasColumnType("int");

                    b.Property<int>("InitialQuantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("366c394a-7818-4b06-94c1-c7525a7f8415"),
                            CurrentQuantity = 100,
                            InitialQuantity = 100,
                            Price = 10.5m,
                            ProductName = "Product A",
                            Unit = "kg"
                        },
                        new
                        {
                            Id = new Guid("7874cf2b-b47e-4df2-b2c4-37c04fc03dd7"),
                            CurrentQuantity = 200,
                            InitialQuantity = 200,
                            Price = 2.0m,
                            ProductName = "Product B",
                            Unit = "pieces"
                        },
                        new
                        {
                            Id = new Guid("31ac27d7-4c50-4dc7-8019-1a4e52a37853"),
                            CurrentQuantity = 50,
                            InitialQuantity = 50,
                            Price = 5.0m,
                            ProductName = "Product C",
                            Unit = "liters"
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.ProductTransaction", b =>
                {
                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TransactionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId", "TransactionId");

                    b.HasIndex("TransactionId");

                    b.ToTable("ProductTransactions");

                    b.HasData(
                        new
                        {
                            ProductId = new Guid("366c394a-7818-4b06-94c1-c7525a7f8415"),
                            TransactionId = new Guid("fa420b22-7309-42d0-a269-fce44df13ad3"),
                            Quantity = 10,
                            TotalPrice = 105.0m
                        },
                        new
                        {
                            ProductId = new Guid("7874cf2b-b47e-4df2-b2c4-37c04fc03dd7"),
                            TransactionId = new Guid("fa420b22-7309-42d0-a269-fce44df13ad3"),
                            Quantity = 20,
                            TotalPrice = 40.0m
                        },
                        new
                        {
                            ProductId = new Guid("366c394a-7818-4b06-94c1-c7525a7f8415"),
                            TransactionId = new Guid("9eacff09-2939-4fc2-b51a-da4c7c2690e3"),
                            Quantity = 5,
                            TotalPrice = 52.5m
                        },
                        new
                        {
                            ProductId = new Guid("31ac27d7-4c50-4dc7-8019-1a4e52a37853"),
                            TransactionId = new Guid("f8d4e395-7dc0-4fbf-b7d3-49e16dee8b9f"),
                            Quantity = 15,
                            TotalPrice = 75.0m
                        },
                        new
                        {
                            ProductId = new Guid("7874cf2b-b47e-4df2-b2c4-37c04fc03dd7"),
                            TransactionId = new Guid("ae9b2941-7140-48bd-a7e8-901ee37e1bf4"),
                            Quantity = 30,
                            TotalPrice = 60.0m
                        },
                        new
                        {
                            ProductId = new Guid("31ac27d7-4c50-4dc7-8019-1a4e52a37853"),
                            TransactionId = new Guid("27a38c3b-7f37-4f3a-96c6-36caf960f805"),
                            Quantity = 25,
                            TotalPrice = 125.0m
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("fa420b22-7309-42d0-a269-fce44df13ad3"),
                            Date = new DateTime(2024, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("9eacff09-2939-4fc2-b51a-da4c7c2690e3"),
                            Date = new DateTime(2024, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("f8d4e395-7dc0-4fbf-b7d3-49e16dee8b9f"),
                            Date = new DateTime(2024, 10, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("ae9b2941-7140-48bd-a7e8-901ee37e1bf4"),
                            Date = new DateTime(2024, 10, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = new Guid("27a38c3b-7f37-4f3a-96c6-36caf960f805"),
                            Date = new DateTime(2024, 10, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("UISTask.Domain.Entities.ProductTransaction", b =>
                {
                    b.HasOne("UISTask.Domain.Entities.Product", "Product")
                        .WithMany("ProductTransaction")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UISTask.Domain.Entities.Transaction", "Transaction")
                        .WithMany("ProductTransactions")
                        .HasForeignKey("TransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Transaction");
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Product", b =>
                {
                    b.Navigation("ProductTransaction");
                });

            modelBuilder.Entity("UISTask.Domain.Entities.Transaction", b =>
                {
                    b.Navigation("ProductTransactions");
                });
#pragma warning restore 612, 618
        }
    }
}
